name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - name: Set up Python "3.11.0"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          make install-dev
      - name: Run CI
        run: make ci